version: '3'

networks:
  def-net:
    driver: bridge

services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 443:443
    networks:
      - def-net
    restart: always
  mariadb:
    build: ./maria
    container_name: mariadb
    ports:
      - 3306:3306
    networks:
      - def-net
    restart: always
  wordpress:
    build: ./wp
    container_name: wordpress
    depends_on:
      - mariadb
    ports: 
      - 9000:9000
    networks:
      - def-net
    restart: always