version: '3'

networks:
  def-net:
    driver: bridge

volumes:
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: ./mariadb

services:
  mariadb:
    build: ./requirements/maria
    container_name: mariadb
    # volumes: 
    #   - db:/var/lib/mysql
    networks:
      - def-net
    env_file:
      - .env
    restart: unless-stopped
  wordpress:
    build: ./requirements/wp
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - def-net
    env_file:
      - .env
    restart: unless-stopped
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - def-net
    volumes:
      - ./wordpress:/var/www/html
    restart: unless-stopped