version: '3'

networks:
  def-net:
    name: def-net
    driver: bridge

volumes:
  wp:
    driver: local
    name: wp
    driver_opts:
      type: none
      o: bind
      device: ./wordpress
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: ./mariadb

services:
  mariadb:
    build: ./maria
    container_name: mariadb
    # volumes:
    #   - db:/var/lib/mysql
    networks:
      - def-net
    restart: unless-stopped

  wordpress:
    build: ./wp
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/html
    networks:
      - def-net
    restart: unless-stopped

  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - def-net
    volumes:
      - wp:/var/www/html
    restart: unless-stopped