version: '3'

networks:
  def-net:
    # name: def-net
    driver: bridge

volumes:
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: ./mariadb

services:
  mariadb:
    build: ./maria
    container_name: mariadb
    # volumes: 
    #   - db:/var/lib/mysql
    networks:
      - def-net
    # expose:
    #   - "3306"
    restart: unless-stopped

  wordpress:
    build: ./wp
    container_name: wordpress
    depends_on:
      - mariadb
    # ports: 
    #   - 9000:9000
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - def-net
    # links:
    #   - mariadb:mysql
    restart: unless-stopped

  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - def-net
    volumes:
      - ./wordpress:/var/www/html
    restart: unless-stopped