version: '3'

networks:
  def-net:
    # name: def-net
    driver: bridge



services:
  mariadb:
    build: ./maria
    container_name: mariadb
    volumes: 
      - /home/hakob/data/mariadb:/var/lib/mysql
    networks:
      - def-net
    # expose:
    #   - "3306"
    restart: unless-stopped

  wordpress:
    build: ./wp
    container_name: wordpress
    depends_on:
      - mariadb
    # ports: 
    #   - 9000:9000
    volumes:
      - /home/hakob/data/wordpress:/var/www/html
    networks:
      - def-net
    # links:
    #   - mariadb:mysql
    restart: unless-stopped

  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - def-net
    volumes:
      - /home/hakob/data/wordpress:/var/www/html
    restart: unless-stopped